version: '3.8'

services:
  # Web application
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/agentexpress
      - SUPABASE_URL=http://supabase:8000
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    depends_on:
      - db
      - redis
    networks:
      - agentexpress-network

  # Database
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=agentexpress
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - agentexpress-network

  # Redis for caching
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - agentexpress-network

  # Supabase local development
  supabase:
    image: supabase/supabase-local:latest
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_PASSWORD=postgres
      - JWT_SECRET=${SUPABASE_JWT_SECRET}
    depends_on:
      - db
    networks:
      - agentexpress-network

  # Mailhog for email testing
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - agentexpress-network

  # Adminer for database management
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - agentexpress-network

  # Minio for S3-compatible storage
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - agentexpress-network

networks:
  agentexpress-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  minio-data:
